# Generated by Django 3.2.5 on 2021-07-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['id_ciudad'], 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['id_pais'], 'verbose_name_plural': 'paises'},
        ),
    ]
