# Generated by Django 3.1.3 on 2021-07-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210727_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_name'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pais',
            table=None,
        ),
    ]
