# Generated by Django 3.2.5 on 2021-07-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210727_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pais',
            name='id_pais',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id_Pais'),
        ),
    ]
