# Generated by Django 3.1.3 on 2021-07-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210726_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuario'},
        ),
    ]
