# Generated by Django 3.1.3 on 2021-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210726_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_card',
            field=models.IntegerField(default=12314123, verbose_name='Nro Tarjeta'),
            preserve_default=False,
        ),
    ]
