# Generated by Django 3.1.3 on 2021-07-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210727_2107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
    ]
