# Generated by Django 3.1.3 on 2021-07-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.PositiveIntegerField(verbose_name='Nro Tarjeta'),
        ),
    ]
