# Generated by Django 3.1.3 on 2021-07-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210727_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': True, 'ordering': ['id_ciudad'], 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True, 'ordering': ['id_pais'], 'verbose_name_plural': 'paises'},
        ),
    ]
