# Generated by Django 3.2.5 on 2021-07-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_ciudad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='id_ciudad',
            new_name='id_city',
        ),
    ]
