# Generated by Django 3.1.3 on 2021-07-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210727_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['id_ciudad'], 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['id_pais'], 'verbose_name_plural': 'paises'},
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', default=2, on_delete=django.db.models.deletion.CASCADE, to='user.pais'),
            preserve_default=False,
        ),
    ]
