# Generated by Django 3.1.3 on 2021-07-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210727_2116'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pais',
            table=None,
        ),
    ]
