# Generated by Django 3.1.3 on 2021-07-26 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210726_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(0)], verbose_name='Nro Tarjeta'),
        ),
    ]
