# Generated by Django 3.1.3 on 2021-07-28 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='user.pais')),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudad',
                'ordering': ['id_ciudad'],
            },
        ),
    ]
