# Generated by Django 3.2.5 on 2021-07-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210728_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city'),
        ),
    ]
