# Generated by Django 3.1.3 on 2021-07-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210726_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.IntegerField(verbose_name='Nro Tarjeta'),
        ),
    ]
