# Generated by Django 3.1.3 on 2021-07-26 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210726_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='safe_code',
            field=models.IntegerField(default=123, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Código de Seguridad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(0)], verbose_name='Nro Tarjeta'),
        ),
    ]
