# Generated by Django 3.2.5 on 2021-07-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210728_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ubication',
        ),
    ]
