# Generated by Django 3.1.3 on 2021-07-26 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210726_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='safe_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='Código de Seguridad'),
        ),
    ]
