# Generated by Django 3.2.5 on 2021-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210728_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Pefil')),
                ('name1', models.CharField(max_length=50, verbose_name='Nombre Perfil 1')),
                ('name2', models.CharField(max_length=50, null=True, verbose_name='Nombre Perfil 2')),
                ('name3', models.CharField(max_length=50, null=True, verbose_name='Nombre Perfil 3')),
                ('name4', models.CharField(max_length=50, null=True, verbose_name='Nombre Perfil 4')),
                ('name5', models.CharField(max_length=50, null=True, verbose_name='Nombre Perfil 5 ')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['name1'],
            },
        ),
    ]
