# Generated by Django 3.2.5 on 2021-07-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['id_perfil'], 'verbose_name': 'perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
