# Generated by Django 3.2.5 on 2021-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id_perfil',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Perfil'),
        ),
    ]
